### ISSUE TITLE
Compatibility with WP 4.4

### ISSUE THREAD

**Issue by ahmadawais** [tommcfarlin/title-capitalization-for-wordpress#13]
This plugin is  not compatible with WP 4.4. I am sure you already know that. Can you tell us when will be releasing the compatible version.

**Comment by tommcfarlin** [comment]
I have no date for when the compatible version will be released other than
[its something I am looking to address when I have a chance](
https://twitter.com/tommcfarlin/status/662298361480011776).

-- Tom

**Comment by ahmadawais** [comment]
@tommcfarlin That's great. I have started watching the repo for updates when you release something.

**Comment by ahmadawais** [comment]
@tommcfarlin  Any updates?

**Comment by afragen** [comment]
Done https://github.com/tommcfarlin/title-capitalization-for-wordpress/pull/15
