### ISSUE TITLE
Error: “You are currently editing the page that shows your latest posts.”

### ISSUE THREAD

**Issue by leftlane** [tommcfarlin/title-capitalization-for-wordpress#14]
When this plugin is activated, the Editor disappears from Add New > Post or Page, replaced with the error, “You are currently editing the page that shows your latest posts.”

Screenshot: http://cl.ly/fa2T

**Comment by ahmadawais** [comment]
@leftlane This plugin was supported until WP 4.1 after that I started having issues and deactivated it. 

P.S. Now, instead of relying on a plugin I built [TitleCaseIt](http://ahmadawais.github.io/TitleCaseIt/) to help me with that.

**Comment by tommcfarlin** [comment]
@leftlane Thanks! I'm working on a new, much more advanced version of this plugin right now. I'm hoping to have it ready for release by the end of April. It'll be more up-to-date, resilient to upgrades, and have some other built-in features that this. I'll have a note in this repository once it's ready.

Until then, @ahmadawais will likely be the best alternative for now.

I'll update the `README` to make a note of all of this.

**Comment by ahmadawais** [comment]
@tommcfarlin Looking forward!

**Comment by leftlane** [comment]
Thanks for the update, @tommcfarlin. I look forward to the new release!

And thanks for the alternative recommendation, @ahmadawais. Unfortunately, I needed this solution for my copywriting team, who — believe it or not — are less than stellar at capitalization rules. _(Don't get me started on the state of our modern education system.)_ But I doubt I could get them to use TitleCaseIt for every headline and sub-heading.

**Comment by ahmadawais** [comment]
@leftlane I feel your pain. I myself write a lot so, it comes in handy.

**Comment by afragen** [comment]
Fixed https://github.com/tommcfarlin/title-capitalization-for-wordpress/pull/15

**Comment by tommcfarlin** [comment]
Props @afragen.

This is going to be officially part of 1.3.0.
