### ISSUE TITLE
Add i18n Support

### ISSUE THREAD

**Issue by tommcfarlin** [tommcfarlin/title-capitalization-for-wordpress#18]
Only half-baked support exists. In `1.3.0`, I want to leverage WordPress 4.6 functionality and introduce the basic `.po` files for translation.

**Comment by afragen** [comment]
I can run it through POEdit.

**Comment by GaryJones** [comment]
If this plugin is in (or going to be in) the .org repo, then no need to even create the `.pot` file.

**Comment by tommcfarlin** [comment]
Right now, there are no plans to add it to the .org report.

**Comment by GaryJones** [comment]
Ping me when you have a `.pot`, and I'll do the en_GB version :-)

**Comment by afragen** [comment]
I added a PR for the `.pot` #29
